config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :players,       only: %i[index create update destroy]
  resources :teams,         only: %i[index create update destroy]
  resources :games,         only: %i[index new create edit update destroy]
  resources :player_scores do
    collection do
      get :batter_score
      get :pitcher_score
    end
  end
end

app/controllers/player_scores_controller.rb
class PlayerScoresController < ApplicationController
  def batter_score; end

  def pitcher_score; end
end

app/helpers/player_scores_helper.rb
module PlayerScoresHelper
end

app/views/player_scores/batter_score.html.slim
.mt-2
  = link_to pitcher_score_player_scores_path do
    button class='rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 hover:bg-blue-700 focus:outline-none focus:shadow-outline'
      = t('view.button.pitcher_scores')

.mt-4.p-2.border.w-full
  table.table-fixed.border-collapse.text-sm
    thead
      tr
        th.border.p-1 背番号
        th.border.p-1 選手
        th.border.p-1 打席数
        th.border.p-1 四死球
        th.border.p-1 犠打
        th.border.p-1 犠飛
        th.border.p-1 得点
        th.border.p-1 安打(長打含む)
        th.border.p-1 打点
        th.border.p-1 三振
        th.border.p-1 盗塁
        th.border.p-1 二塁打
        th.border.p-1 三塁打
        th.border.p-1 本塁打
        th.border.p-1 失策
        th.border.p-1 打数
        th.border.p-1 打率
        th.border.p-1 出塁率
        th.border.p-1 長打率
        th.border.p-1 OPS
        th.border.p-1 塁打数
        th.border.p-1 出席数
        th.border.p-1 出席率
    tbody
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1.w-24 鈴木 将平
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 源田 壮亮
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 外崎 修汰
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 山川 穂高
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 森 友哉
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 中村 剛也
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 栗山 巧
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 熊代 聖人
      tr
        td.border.text-center.p-1 8
        td.border.text-center.p-1 木村 文紀

app/views/player_scores/pitcher_score.html.slim
.mt-2
  = link_to batter_score_player_scores_path do
    button class='rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 hover:bg-blue-700 focus:outline-none focus:shadow-outline'
      = t('view.button.batter_scores')

.mt-4.p-2.border.w-full
  table.table-fixed.border-collapse.text-sm
    thead
      tr
        th.border.p-1 背番号
        th.border.p-1 選手
        th.border.p-1 完了イニング
        th.border.p-1 途中アウト
        th.border.p-1 打者数
        th.border.p-1 投球数
        th.border.p-1 被安打
        th.border.p-1 被本塁打
        th.border.p-1 奪三振
        th.border.p-1 与四死球
        th.border.p-1 自責点
        th.border.p-1 勝利
        th.border.p-1 敗戦
        th.border.p-1 セーブ
        th.border.p-1 ホールドポイント
        th.border.p-1 投球アウト
        th.border.p-1 防御率
        th.border.p-1 被打率
        th.border.p-1 奪三振率
    tbody
      tr
        td.text-center.p-1
        td.border.text-center.p-1 今井 達也
      tr
        td.text-center.p-1
        td.border.text-center.p-1 平良 海馬
      tr
        td.text-center.p-1
        td.border.text-center.p-1 ギャレット
      tr
        td.text-center.p-1
        td.border.text-center.p-1 増田 達至