config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :players,       only: %i[index create update destroy]
  resources :teams,         only: %i[index create update destroy]
  resources :games,         only: %i[index new create edit update destroy]
  resources :player_scores do
    collection do
      get :batter_score
      get :pitcher_score
    end
  end
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id               :bigint           not null, primary key
#  matched_at       :datetime         not null              # 試合日
#  result           :integer          not null              # 勝敗結果
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  opponent_team_id :bigint           not null              # 相手チーム
#  own_team_id      :bigint           not null              # 自チーム
#
# Indexes
#
#  index_games_on_opponent_team_id  (opponent_team_id)
#  index_games_on_own_team_id       (own_team_id)
#
# Foreign Keys
#
#  fk_rails_...  (opponent_team_id => teams.id)
#  fk_rails_...  (own_team_id => teams.id)
#
class Game < ApplicationRecord
  has_many :inning_scores
  has_many :batter_scores

  belongs_to :team

  accepts_nested_attributes_for :inning_scores, allow_destroy: true
  accepts_nested_attributes_for :batter_scores, allow_destroy: true

  validates :own_team_id, presence: true
  validates :opponent_team_id, presence: true
  validates :result, presence: true
  validates :matched_at, presence: true

  enum result: { win: 0, lose: 1 }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = current_team.games
  end

  def new
    @game = current_team.games.build
    @teams = Team.all
    @opponent_teams = Team.opponent_teams
    @inning_scores = @game.inning_scores.build
    @batting_scores = @game.batter_scores.build
  end

  def create
    game = current_team.games.build(permit_params)
    if game.save
      redirect_to games_path(game), notice: I18n.t('view.flash.registrate', name: I18n.t('activerecord.models.game'))
    else
      render :new
    end
  end

  def edit
    @game = current_team.games.find(params[:id])
    @inning_scores = @game.inning_scores
  end

  def update
    game = current_team.games.find(params[:id])
    if game.update
      redirect_to games_path(game), notice: I18n.t('view.flash.update', name: I18n.t('activerecord.models.game'))
    else
      render :edit
    end
  end

  def destroy
    game = current_team.games.find(params[:id])
    if game.destroy
      redirect_to games_path, notice: I18n.t('view.flash.destroy', name: I18n.t('activerecord.models.game'))
    else
      render :edit
    end
  end

  private

  def permit_params
    params.permit(:own_team_id, :opponent_team_id, :result, :matched_at,
                  inning_scores_attributes: %i[id inning order score game_id team_id _destroy])
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def team_select_value(teams)
    teams.map {|team| [team.name, team.id]}
  end

  def position_select_value
    Position.all.map {|position| [position.name_short, position.id]}
  end

  def player_select_value
    @current_team.players.map {|player| [player.full_name, player.id]}
  end
end

app/views/games/_batter_score_fields.html.slim
tr
  td.text-center.p-1 = render 'icons/plus'
  td.border.text-center.p-1
    = order
  td.border.text-center.p-1
    = f.select :position_id, position_select_value, {include_blank: true}, {class: 'w-full bg-gray-200 px-6 rounded appearance-none leading-tight focus:outline-none'}
  td.border.text-center.p-1
    = f.select :player_id, player_select_value, {include_blank: true}, {class: 'w-full bg-gray-200 px-2 rounded appearance-none leading-tight focus:outline-none'}
  td.border.text-center.p-1
    = f.number_field :bats, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :four_dead_ball, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :bunt, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :sacrifice_fly, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :score, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :hit, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :rbi, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :strikeout, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :steal, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :two_bases, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :three_bases, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :homerun, class: 'text-right w-10'
  td.border.text-center.p-1
    = f.number_field :error, class: 'text-right w-10'

app/views/games/_form.html.slim
- url = game.new_record? ? games_path : game_path

= form_with model: game, url: url do |f|
  .block
    = f.label :matched_at, "#{ t('activerecord.attributes.game.matched_at') }・#{ t('activerecord.attributes.game.opponent_team') }"
  .mt-2
    = f.date_select :matched_at, {}, { class: 'appearance-none bg-gray-100 border text-sm border-gray-200 text-gray-800 py-3 px-4 rounded leading-tight focus:outline-none' }
    = f.select :opponent_team_id, team_select_value(@opponent_teams), { include_blank: true }, { class: 'appearance-none bg-gray-100 text-sm border border-gray-200 text-gray-800 py-3 px-4 rounded leading-tight focus:outline-none' }

  .mt-2
    table.border.table-fixed.border-collapse.text-sm
      thead
        tr
          th.border.w-56 = t('view.score_board.team_name')
          th.border.w-10 1
          th.border.w-10 2
          th.border.w-10 3
          th.border.w-10 4
          th.border.w-10 5
          th.border.w-10 6
          th.border.w-10 7
          th.border.w-10 = t('view.score_board.total_score')
      tbody
        = f.fields_for :inning_scores, @inning_scores do |is|
          = is.hidden_field :order, value: InningScore.orders[:top]
          = render 'score_board_fields', f: is, teams: teams

        = f.fields_for :inning_scores, @inning_scores do |is|
          = is.hidden_field :order, value: InningScore.orders[:bottom]
          = render 'score_board_fields', f: is, teams: teams

  .mt-2.p-2.border.w-full
    table.table-fixed.border-collapse.text-sm
      thead
        tr
          th
          th.border.p-1 = t_ar('GameBattingScore.order')
          th.border.p-1 = t_ar('GameBattingScore.position_id')
          th.border.p-1 = t_ar('BatterScore.player_id')
          th.border.p-1 = t_ar('BatterScore.bats')
          th.border.p-1 = t_ar('BatterScore.four_dead_ball')
          th.border.p-1 = t_ar('BatterScore.bunt')
          th.border.p-1 = t_ar('BatterScore.sacrifice_fly')
          th.border.p-1 = t_ar('BatterScore.score')
          th.border.p-1 = t_ar('BatterScore.hit')
          th.border.p-1 = t_ar('BatterScore.rbi')
          th.border.p-1 = t_ar('BatterScore.strikeout')
          th.border.p-1 = t_ar('BatterScore.steal')
          th.border.p-1 = t_ar('BatterScore.two_bases')
          th.border.p-1 = t_ar('BatterScore.three_bases')
          th.border.p-1 = t_ar('BatterScore.homerun')
          th.border.p-1 = t_ar('BatterScore.error')
      tbody
        - 9.times do |t|
          = f.fields_for :batter_scores, @batter_scores do |bs|
            = render 'batter_score_fields', f: bs, order: t + 1

  .mt-2.p-2.border.w-full
    table.table-fixed.border-collapse.text-sm
      thead
        tr
          th
          th.border.p-1 = t_ar('PitcherScore.player_id')
          th.border.p-1 = t_ar('PitcherScore.completion_inning')
          th.border.p-1 = t_ar('PitcherScore.out_count')
          th.border.p-1 = t_ar('PitcherScore.batter_count')
          th.border.p-1 = t_ar('PitcherScore.pitching_count')
          th.border.p-1 = t_ar('PitcherScore.hit')
          th.border.p-1 = t_ar('PitcherScore.homerun')
          th.border.p-1 = t_ar('PitcherScore.strikeout')
          th.border.p-1 = t_ar('PitcherScore.walk_dead_ball')
          th.border.p-1 = t_ar('PitcherScore.self_responsibility')
          th.border.p-1 = t_ar('PitcherScore.wins')
          th.border.p-1 = t_ar('PitcherScore.losses')
          th.border.p-1 = t_ar('PitcherScore.save_count')
          th.border.p-1 = t_ar('PitcherScore.hold_point')
      tbody
        = render 'pitcher_score_fields'

  .flex.justify-end
    = f.submit t('view.button.registrate'), class: 'rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 mt-2 hover:bg-blue-700 focus:outline-none focus:shadow-outline'

app/views/games/_pitcher_score_fields.html.slim
tr
  td.text-center.p-1 = render 'icons/plus'
  td.border.text-center.p-1 今井 達也
tr
  td.text-center.p-1 = render 'icons/plus'
  td.border.text-center.p-1 平良 海馬
tr
  td.text-center.p-1 = render 'icons/plus'
  td.border.text-center.p-1 ギャレット
tr
  td.text-center.p-1 = render 'icons/plus'
  td.border.text-center.p-1 増田 達至

app/views/games/_score_board_fields.html.slim
tr.text-center
  td.border
    = f.select :team_id, team_select_value(teams), { include_blank: true }, { class: 'appearance-none leading-tight focus:outline-none' }
  - 7.times do |t|
    td.border
      = f.hidden_field :inning, value: t + 1
      = f.number_field :score, class: 'w-10 text-right'
  td.border 0

app/views/games/edit.html.slim
h1 Games#edit
p Find me in app/views/games/edit.html.slim

app/views/games/index.html.slim
- image = Rails.env.development? ? 'seibu_logo.jpg' : 'eclea_logo.png'

.mt-2
  article class="rounded shadow max-w-md flex mx-auto p-4"
    div
      = image_tag(image, class: 'rounded-full w-40')
    div.flex.flex-col.p-4
      p.text-xl
        = current_team.name
      p.text-xl.mt-2
        | 2020年度成績
      p.text-xl.mt-2
        | 〇〇勝〇〇敗

  div.flex.justify-end
    = link_to new_game_path, class: 'rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 mt-2 hover:bg-blue-700 focus:outline-none focus:shadow-outline' do
      = t('view.button.new')

app/views/games/new.html.slim
.mt-2
  = render 'form', game: @game, teams: (@teams)