config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :players,       only: %i[index create update destroy]
  resources :teams,         only: %i[index create update destroy]
  resources :games,         only: %i[index new create edit update destroy]
  resources :player_scores do
    collection do
      get :batter_score
      get :pitcher_score
    end
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :bigint           not null, primary key
#  first_name :string           not null              # 名
#  last_name  :string           not null              # 姓
#  number     :integer          not null              # 背番号
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :bigint           not null              # 紐付け先のチームid
#
# Indexes
#
#  index_players_on_team_id  (team_id)
#
class Player < ApplicationRecord
  has_many :batter_score

  belongs_to :team

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :number, presence: true
  validates :team_id, presence: true
  validate :invalid_same_number

  scope :same_team_players, ->(team_id) { where(team_id: team_id) }

  def full_name
    "#{last_name} #{first_name}"
  end

  private

  def invalid_same_number
    return unless Player.same_team_players(team_id).where.not(id: id).pluck(:number).include?(number)

    errors[:base] << I18n.t('custom_errors.invalid_same_player_number')
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = current_team.players.all
    @player = current_team.players.build
  end

  def create
    @players = current_team.players.all
    player = current_team.players.build(permit_params)

    if player.save
      redirect_to players_path, notice: I18n.t('view.flash.registrate', name: player.full_name)
    else
      flash.now[:danger] = t('view.flash.error_registrate')
      render :index
    end
  end

  def update
    @players = current_team.players.all
    player = current_team.players.find(params[:id])

    if player.update(permit_params)
      redirect_to players_path, notice: I18n.t('view.flash.update', name: player.full_name)
    else
      flash.now[:danger] = t('view.flash.error_update')
      render :index
    end
  end

  def destroy
    player = Player.find(params[:id])
    if player.destroy
      redirect_to players_path, notice: I18n.t('view.flash.delete', name: player.full_name)
    else
      flash.now[:danger] = t('view.flash.error_destroy')
      render :index
    end
  end

  private

  def permit_params
    params.permit(:first_name, :last_name, :number)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.slim
form.flex.justify-between.mt-6
  input.shadow.border.rounded.appearance-none.text-gray-700.text-sm.font-bold.p-2 class='w-10/12 focus:shadow-outline focus:outline-none' placeholder="#{ t('view.search_by.player_full_name') }"
  input.shadow.border.rounded.appearance-none.text-gray-700.text-sm.font-bold.p-2 class='w-1/12 focus:shadow-outline focus:outline-none' placeholder="#{ t('view.search_by.player_number') }"
  button.rounded.bg-blue-500.text-white.font-bold.py-2.px-4 class='hover:bg-blue-700 focus:outline-none focus:shadow-outline'
    = t('view.button.search')

.registrate-team.mt-2
  = form_with model: @player, class: 'flex justify-end', local: true do |f|
    div
      = f.label :last_name, class: 'text-gray-700 text-xs font-bold'
      = f.text_field :last_name, class: 'shadow border rounded block appearance-none text-gray-700 text-sm font-bold p-2 w-11/12 focus:shadow-outline focus:outline-none'

    div
      = f.label :first_name, class: 'text-gray-700 text-xs font-bold'
      = f.text_field :first_name, class: 'shadow border rounded block appearance-none text-gray-700 text-sm font-bold p-2 w-11/12 focus:shadow-outline focus:outline-none'

    div
      = f.label :number, class: 'text-gray-700 text-xs font-bold'
      = f.number_field :number, class: 'shadow border rounded block appearance-none text-gray-700 text-sm font-bold p-2 w-11/12 focus:shadow-outline focus:outline-none'

    span.flex.flex-col.justify-end
      = f.submit t('view.button.registrate'), class: 'rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 mt-2 hover:bg-blue-700 focus:outline-none focus:shadow-outline'

table.table-fixed.border-collapse.w-full.mt-6
  thead
    tr.bg-gray-300
      th.p-1.border class='w-1/12' = t('activerecord.attributes.player.number')
      th.p-1.border class='w-10/12' = t('activerecord.attributes.player.full_name')
      th.p-1.border
  tbody
    - @players.each do |player|
      tr class='hover:bg-green-100'
        td.border.px-2.py-1.text-center = player.number
        td.border.px-2.py-1 = player.full_name
        td.border.px-2.py-1
          span.flex.justify-around
            button class="focus:outline-none" id="player-edit-#{ player.id }"
              = render 'icons/edit', optional_class: 'w-6'
            = link_to player_path(player),  method: :delete, data: { confirm: t('view.confirm.delete') } do
              = render 'icons/trash', optional_class: 'w-6'
      tr class="player-edit-#{ player.id }-tr hidden"
        td class='border' colspan='3'
          = form_with url: player_path(player), method: :patch, class: 'flex', local: true do |f|
            = f.text_field :last_name, placeholder: t('activerecord.attributes.player.last_name'), value: player.last_name, class: 'w-2/5 shadow block rounded appearance-none text-gray-700 text-sm font-bold p-2 focus:outline-none'
            = f.text_field :first_name, placeholder: t('activerecord.attributes.player.first_name'), value: player.first_name, class: 'w-2/5 shadow block rounded appearance-none text-gray-700 text-sm font-bold p-2 focus:outline-none'
            = f.number_field :number, placeholder: t('activerecord.attributes.player.number'), value: player.number, class: 'w-1/5 shadow border rounded block appearance-none text-gray-700 text-sm font-bold p-2 focus:outline-none'
            = f.submit t('view.button.update'), class: 'rounded bg-blue-500 text-sm text-white font-bold py-2 px-4 hover:bg-blue-700 focus:outline-none focus:shadow-outline'

= javascript_pack_tag('players')