config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :players,       only: %i[index create update destroy]
  resources :teams,         only: %i[index create update destroy]
  resources :games,         only: %i[index new create edit update destroy]
  resources :player_scores do
    collection do
      get :batter_score
      get :pitcher_score
    end
  end
end

app/views/layouts/_header.html.slim
header.bg-gray-700
  article.container.mx-auto.p-4.flex.justify-between
    h2.text-base.text-gray-100 = t("page_title.#{ controller_name }")
    nav.text-gray-100
      ul.flex
        li
          = link_to t('view.header.players'), players_path
        li.ml-4
          = link_to t('view.header.teams'), teams_path
        li.ml-4
          = link_to t('view.header.games'), root_path
        li.ml-4
          = link_to t('view.header.player_scores'), batter_score_player_scores_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('application_name')
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container.mx-auto.px-4
      #alert.mt-4
        - flash.each do |key, value|
          - if key == 'notice'
            = content_tag(:div, class: 'bg-teal-200 border border-teal-200 text-teal-700 px-4 py-3 rounded relative') do
              span class='block sm:inline'
                = value.html_safe
          - else
            = content_tag(:div, class: 'bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative')
              span class='block sm:inline'
                = value.html_safe

      = yield